version: '3.5'

services:

  db:
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: prodespass
        POSTGRES_USER: prodesuser
        POSTGRES_DB: reactfullstack
      ports: 
        - 5432:5432
      volumes:
        #- ./initdb/reactfullstack.sql:/docker-entrypoint-initdb.d/reactfullstack.sql
        - ./pgdata:/var/lib/postgresql/data
      
        
  sample-app:
    container_name: fullstack
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - db
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    command: bash -c 'chmod +x wait-for-it.sh && ./wait-for-it.sh db:5432 -- npm run seed && npm start'
    # command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; npm run seed && npm start' # - works
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - SEQ_DB=reactfullstack
      - SEQ_USER=prodesuser
      - SEQ_PW=prodespass
      #- PORT=4242
      - DATABASE_URL=postgres://prodesuser:prodespass@db:5432/reactfullstack
    links:
      - db